name: CI - Test

on:
  workflow_dispatch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout üîî
        uses: actions/checkout@v4

      - name: Docker Metadata üè∑Ô∏è
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            binary-braids/github-actions-runner          
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Setup QEMU üñ•Ô∏è
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx üñ•Ô∏è
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry üîì
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io  
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}       
          
      - name: Build and push üèóÔ∏è
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get First Tag from Image üè∑Ô∏è
        id: get_first_tag
        run: |
          echo "first_tag=$(echo "${{ steps.meta.outputs.tags }}" | awk -F, '{print $1}')" >> $GITHUB_OUTPUT

      - name: Run Trivy Vulnerability Scanner üè∞
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.get_first_tag.outputs.first_tag }}
          format: 'table'
          vuln-type: 'os,library'
          severity: "MEDIUM,HIGH,CRITICAL"
